services:
   _defaults:
      autowire: true
      autoconfigure: true
      public: false
      
   WEBcoast\Recipes\:
      resource: '../Classes/*'
      exclude:
         - '../Classes/Domain/Model/*'
